### PR TITLE
fix versioneer cmdclass

### PR DESCRIPTION
**Pull request by ocefpaf**
I forgot this part in PR #138

### CODE REVIEW

**Comment by emiliom** [comment]
AppVeyor failed. Should I merge, or wait for you to look into it?

**Comment by ocefpaf** [comment]
I am looking into it. The failure is quite odd :confused:

**Comment by ocefpaf** [comment]
OK. It was already failing before and it is related to PR https://github.com/ODM2/WOFpy/pull/147
Apparently we did not notice the failure when merging it.

**Comment by emiliom** [comment]
> It was already failing before and it is related to PR #147

That rings a bell. Anyway, I'll merge.

**Comment by emiliom** [comment]
Oh, and appveyor is not failing anymore?!

**Comment by ocefpaf** [comment]
> That rings a bell. 

I did not noticed it.

> Oh, and appveyor is not failing anymore?!

Yep. I fixed in https://github.com/ODM2/WOFpy/pull/149/commits/ca7fad08174da580705b331af1bef3664ddd144e

**Pull request merged**
