### PR TITLE
use versioneer

### PR DESCRIPTION
**Pull request by ocefpaf**
Similar to https://github.com/ODM2/ODM2PythonAPI/pull/84

Note that the tags are inconsistent in the git history, some start with `v` while others do not:

```
0.1-alpha
0.2-alpha
2.0.0004-alpha
2.0.0004-alphs
2.0.10b0
2.0.11b0
v2.0-alpha
v2.0.0002-alpha
v2.0.0006-alpha
v2.0.0008-alpha
v2.0.0009-alpha
v2.0.002-alpha
v2.0.003-alpha
```

we need to adhere to a standard in order to use `versioneer `. (I am using the `v` in this PR btw)

### CODE REVIEW

**Comment by lsetiawan** [comment]
Have no idea what this is, but looks good. :)

**Comment by emiliom** [comment]
> we need to adhere to a standard in order to use versioneer. (I am using the v in this PR btw)

But we don't need to change tags for previous releases, right?? We only need to adhere to a standard in future releases?

Otherwise, you're the `versioneer` pro, so I trust you know what you're doing :|

**Comment by emiliom** [comment]
... and go ahead and merge yourself -- though I know you don't like merging your own PR's!

**Comment by ocefpaf** [comment]
> Have no idea what this is, but looks good. :)

The goal is to manage the version string with GitHub tags only and get the version propagate everywhere, reducing the maintenance burden and common mistakes (like bumping a version but forgetting to change the string).

> But we don't need to change tags for previous releases, right??

We don't. All I am saying is that we should standardize it from now on. Right now, for example, if we go with the prefix `v` `versioneer` will wrongfully create version `2.0.9a0` which is based on tag `v2.0.0009-alpha`.

Note that by following versioning rules all those `0` are ignored and `0009` is considered higher than `003`. Also, all the tags without the `v` were ignored, including the latest one :unamused:

> We only need to adhere to a standard in future releases?

Yep. All we need to do it to issue a new "healthy" tag once we merge this and ignore the old ones.

**Pull request merged**
