### PR TITLE
Vocabulary handling overhaul to support ODM2 DAO needs

### PR DESCRIPTION
**Pull request by emiliom**
- Refactored vocabularies module to generalize the checkers and add additional, optional capabilities.
- Iplemented optional pass-through of CV terms (for ODM2 support) for some CVs. 

Starts addressing https://github.com/ODM2/WOFpy/issues/160; more work is needed, but @lsetiawan is working on that

### CODE REVIEW

**Comment by lsetiawan** [comment]
I have confirmed this works.

### Before
```xml
<variable>
<variableCode default="true" vocabulary="postgresqlodm2timeseries" variableID="11">Decagon_CTD-10_EC</variableCode>
<variableName>Electrical conductivity</variableName>
<valueType>Unknown</valueType>
<dataType>Average</dataType>
<generalCategory>Unknown</generalCategory>
<sampleMedium>Unknown</sampleMedium>
<unit>
<unitName>Microsiemen per Centimeter</unitName>
<unitType>Dimensionless</unitType>
<unitAbbreviation>uS/cm</unitAbbreviation>
<unitCode>373</unitCode>
</unit>
```

### After

```xml
<variable>
<variableCode default="true" vocabulary="postgresqlodm2timeseries" variableID="11">Decagon_CTD-10_EC</variableCode>
<variableName>Electrical conductivity</variableName>
<valueType>ASSIGN ME</valueType>
<dataType>Average</dataType>
<generalCategory>Water quality</generalCategory>
<sampleMedium>Unknown</sampleMedium>
<unit>
<unitName>Microsiemen per Centimeter</unitName>
<unitType>Electrical conductivity</unitType>
<unitAbbreviation>uS/cm</unitAbbreviation>
<unitCode>373</unitCode>
</unit>
```

**Comment by lsetiawan** [comment]
@ocefpaf Help! Failure is in `test_cli.py` https://travis-ci.org/ODM2/WOFpy/jobs/270167418#L1113

**Comment by ocefpaf** [comment]
It seems  unrelated to your changes here. It should also be harmless, I am guessing something is different in the new Travis-CI image and/or how the UUID is reported changed.

See that `104556608 != 104556608` is not different actually :smile: it must be an `int` and a `str` or something like that (Yay for Python polymorphism!).

I'll fix it soon, feel free to merge this whenever you are ready.

**Comment by lsetiawan** [comment]
PER @ocefpaf Merging this PR. Thanks!

**Pull request merged**
