### PR TITLE
Fix little spelling errors

### PR DESCRIPTION
**Pull request by lsetiawan**
Just little spelling error fixes.

### CODE REVIEW

**Comment by lsetiawan** [comment]
@ocefpaf Why did the appveyor broke for this one?

**Comment by ocefpaf** [comment]
> @ocefpaf Why did the appveyor broke for this one?

It did not break. The PR was merged before it finished: https://ci.appveyor.com/project/ocefpaf/wofpy-4g2xh/build/1.0.73

It is fine to skip the CIs from simple PRs but bare in mind that `docpot` text **is** converted to code :wink: 

PS0: The tests passed on `master`.
PS1: We don't have test coverage for the CLI yet, so it would not matter anyways.

**Comment by lsetiawan** [comment]
Ah. Okay. Thanks for the explanation 😃

**Comment by emiliom** [comment]
> The PR was merged before it finished

My bad. Got impatient, as it was just a fix to the spelling of two words

**Pull request merged**
