### PR TITLE
Update ini

### PR DESCRIPTION
**Pull request by lsetiawan**
This enables `lazy-apps` mode. Helps Postgresql to work. Solved #133

### CODE REVIEW

**Comment by emiliom** [comment]
@lsetiawan, why are CI checks failing on this commit?? That's weird. I didn't expect any impact from this change.

I was waiting to see those CI tests to complete before merging; I see you've merged now. Still, any thoughts on those failures?

**Comment by lsetiawan** [comment]
@emiliom Yea. I thought that was weird too. It appears that Travis CI is failing at https://travis-ci.org/ODM2/WOFpy/jobs/237613666#L638

when trying to run `build_cbi_cache.py` getting this error: 

lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

**Comment by emiliom** [comment]
I hadn't seen the CI tests fail in a couple of weeks. So this was unexpected ...

**Comment by lsetiawan** [comment]
Yea, looking into it.

**Comment by emiliom** [comment]
After looking at the messages in the TravisCI link you provided, I suspect it's not worth your time right now. My hunch is that it's best to move the cbi test (`test_cbi_parser.py`?) to the set of tests that don't cause TravisCI failures. But @ocefpaf is probably traveling right now.

The [test fails when](https://travis-ci.org/ODM2/WOFpy/jobs/237613666#L660) looking at file `/tmp/cbi_parameter_file.xml`, which appears to be a cached file. But that location seems odd.

We don't care much about the cbi test right now. So, we can look at it again when Filipe is back. Can you open a new targeted issue with the info you have here, plus what I've pasted? Thanks!

**Comment by ocefpaf** [comment]
I am looking into this. Not sure that triggered the failure yet.

(But I am prioritizing the wofpy CLI script so we can issue the new release.)

**Comment by emiliom** [comment]
> I am looking into this. Not sure that triggered the failure yet.

Thanks. Follow-ups should be done at #135

> (But I am prioritizing the wofpy CLI script so we can issue the new release.)

:+1:

**Pull request merged**
