### PR TITLE
Fix dataType and add generalCategory

### PR DESCRIPTION
**Pull request by lsetiawan**
This addresses `dataType` and `generalCategory` for #152.

### CODE REVIEW

**Comment by emiliom** [comment]
@lsetiawan, thanks. Give me a chance to review this first, and also to comment on issue #152. But, not till Monday, unfortunately ...

**Comment by lsetiawan** [comment]
@emiliom Sounds good. I'll leave this here until your approval. Thanks.

**Comment by emiliom** [comment]
@lsetiawan, I think it'd be helpful to be able to run specific tests on this, before merging into master. Would it add much complexity to create a branch instead of PR to master, and then install that branch locally to run against a known test DB (eg, SQLite, or our AWS-based MySQL and PostgreSQL databases)? I've been browsing the wofpy code per your pointers, to start wrapping my head around this.

**Comment by lsetiawan** [comment]
@emiliom I have tested these changes against the AWS-based MySQL that we have.

**Comment by emiliom** [comment]
I'll merge this (it really is an improvement!), and follow up on my comments in #152 about more comprehensive, more 1.1 compliant mappings for these two CV's.

**Pull request merged**
