### PR TITLE
Update production installation notes

### PR DESCRIPTION
**Pull request by lsetiawan**

### CODE REVIEW

**Comment by emiliom** [comment]
@lsetiawan, it looks like the document updates you've made assume WOFpy has been installed via a conda package that includes Filipe's new changes, including `wofpy_config.py`. Is that correct? If so, that's not what we have yet. My understanding is that, until a new conda package is created, the only thing that has changed from a user's point of view is the file path location of the example code that needs to be copied after git cloning (you also removed the `git clone` step).

Let me know if that's true. I won't merge the PR until I hear back.

**Comment by lsetiawan** [comment]
Hi Emilio,

Yea. That's correct. Darn. I will roll back and just change the file path.
Thanks. Sorry.

Best,
Don

**Comment by emiliom** [comment]
My suggestion is to keep those changes in a branch of yours (ie, don't get rid of them completely!). We'll want them eventually, once a new conda package is released. But yeah, at this time, we only want the changes that will allow someone following your instructions **today** to install and configure WOFpy. Thanks.

**Comment by lsetiawan** [comment]
Closing this for now.

**Pull request closed without merging**
