### PR TITLE
Split examples between working and not working

### PR DESCRIPTION
**Pull request by ocefpaf**
@emiliom this PR moves the untested examples out of the package like we discussed last week.

(That way we don't ship things we don't know if it is working or not :smile:)

### CODE REVIEW

**Comment by emiliom** [comment]
Thanks. Just for the record (I think I said it elsewhere), we'll want to bring back odm_1_1 later.

Would it be too much of a hassle for you to rename the new folder to "examples_may_not_work" rather than "examples_do_not_work"??

**Comment by ocefpaf** [comment]
> Would it be too much of a hassle for you to rename the new folder to "examples_may_not_work" rather than "examples_do_not_work"?

No problem. The last commit should do it.

**Comment by emiliom** [comment]
@ocefpaf, I just realized that you placed the new folder `examples_may_not_work` at the base of the repo. I didn't notice that before (didn't pay enough attention). I thought that on Friday you had said it was better to place it at the same level as `examples` -- ie, under the `wof` directory?

**Comment by ocefpaf** [comment]
>  I thought that on Friday you had said it was better to place it at the same level as `examples` -- ie, under the `wof` directory?

I can do that but the reason I placed in under the root was to avoid getting it into the source distribution. But since the same can be accomplished with the MANIFEST file I will do that then.

**Comment by emiliom** [comment]
I vaguely remember you mentioning something about the MANIFEST file. I don't have a strong preference either way, just a slight preference to having the new folder "next to" `wof/examples`, so it can be found and identified more easily.

**Comment by ocefpaf** [comment]
Using the manifest is cleaner. I don't recall why I did that. See #103

**Pull request merged**
