### PR TITLE
fix needed for LCZO WOF deployment

### PR DESCRIPTION
**Pull request by miguelcleon**
see #219

### CODE REVIEW

**Comment by emiliom** [comment]
@miguelcleon I'm glad you found a solution! But let's wait for @lsetiawan to evaluate this and confirm that it doesn't impact deployments nginx; I'm guessing it's possible that setting has to be different for nginx vs apache.

**Comment by miguelcleon** [comment]
@emiliom Yes, I was thinking that maybe the case. If so, maybe apache or nginx can be detected if not a setting maybe needed.

**Comment by lsetiawan** [comment]
@miguelcleon @emiliom After doing testing deploying this in a production mode. The change that @miguelcleon has made doesn't impact deployment with `nginx`. Thanks. I am merging this PR.

**Comment by miguelcleon** [comment]
@lsetiawan great, thanks! Testing on HIS central QA system isn't working so I'm in communication with @martinseul about that.

**Comment by emiliom** [comment]
Great to see this had no impact on nginx.

**Pull request merged**
