### PR TITLE
AppVeyor configuration.

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR adds a testing framework for Windows.

### CODE REVIEW

**Comment by lsetiawan** [comment]
@ocefpaf I amazed how well you know this stuff! So COOL! 😺

**Comment by ocefpaf** [comment]
The same way I'm amazed by your knowledge of databases :wink:

**Comment by lsetiawan** [comment]
WOO HOO! BUILD SUCCESS ON WINDOWS! SO EXCITING 😃

**Comment by ocefpaf** [comment]
@emiliom and @lsetiawan I believe we are OK to issue a new release. What do you think?

**Comment by lsetiawan** [comment]
@ocefpaf I just noticed the `conda.recipe` folder. Is that needed?

**Comment by ocefpaf** [comment]
> @ocefpaf I just noticed the conda.recipe folder. Is that needed?

Yes. On Windows we test the packaging/build/unittest using conda for convenience. See https://github.com/ODM2/WOFpy/pull/108/files#diff-180360612c6b8c4ed830919bbb4dd459R37

**Comment by lsetiawan** [comment]
> @emiliom and @lsetiawan I believe we are OK to issue a new release. 

I think we need to update the README first before another release to include things about the `wofpy_config`.

**Comment by ocefpaf** [comment]
Indeed. I'll do it tomorrow. (Time to stop for today.)

**Comment by lsetiawan** [comment]
@ocefpaf Enjoy the rest of your day! Thanks for all your awesome work today 😸

**Comment by emiliom** [comment]
Thanks for all your great work!

Let's wait until I'm back, next week, before issuing a new release. I'd
like the chance to review where we are and what was done this week.

Greetings from an airport in DC, before I head to North Carolina.
Emilio

**Pull request merged**
